import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Override default ignores of eslint-config-next.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Generated by @serwist/next at build time — the same files as
    // frontend/.gitignore's "Generated by @serwist/next" entry. Because they
    // are gitignored, a `git checkout` never removes them: build once, switch
    // branches, and lint would otherwise report ~90 problems in a 47KB file
    // nobody wrote.
    "public/sw.js",
    "public/sw.js.map",
    "public/swe-worker-*.js",
  ]),
]);

export default eslintConfig;
